# Generated by Django 3.1.14 on 2022-07-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_for',
            field=models.CharField(choices=[('R', 'Rent'), ('S', 'Sell')], default='S', max_length=5, verbose_name='Listing for'),
        ),
    ]
