# Generated by Django 3.1.14 on 2022-07-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20220723_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addlistings',
            name='title',
        ),
        migrations.AddField(
            model_name='addlistings',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='addlistings',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='addlistings',
            name='location',
            field=models.CharField(max_length=250, null=True, verbose_name='Locations'),
        ),
        migrations.AddField(
            model_name='addlistings',
            name='name',
            field=models.CharField(max_length=120, null=True, verbose_name='Listings Name'),
        ),
        migrations.AddField(
            model_name='addlistings',
            name='phone',
            field=models.CharField(max_length=25, null=True, verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='addlistings',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Descriptions'),
        ),
        migrations.AlterField(
            model_name='addlistings',
            name='owner',
            field=models.CharField(max_length=200, verbose_name='Listing Owner'),
        ),
        migrations.AlterField(
            model_name='addlistings',
            name='price',
            field=models.CharField(max_length=15, verbose_name='Price'),
        ),
    ]
