# Generated by Django 3.1.14 on 2022-07-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20220723_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='addlisting',
            name='listing_type',
            field=models.CharField(choices=[('1', 'House'), ('2', 'Land'), ('3', 'Apartment')], max_length=1, null=True, verbose_name='types'),
        ),
        migrations.AlterField(
            model_name='addlisting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price'),
        ),
    ]
