# Generated by Django 3.1.14 on 2022-07-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20220724_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addlisting',
            old_name='owner_docs',
            new_name='owner_docs_first',
        ),
        migrations.AddField(
            model_name='addlisting',
            name='owner_docs_second',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='addlisting',
            name='owner_docs_third',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
